### ISSUE TITLE
Labels are misplaced/misaligned

### ISSUE THREAD

**Issue by dhoebbel** [okviz/synoptic-panel-issues#4] opened 2023-11-25 16:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm having an issue where the data labels for my synoptic panel/svg visualization are misaligned. When choosing the "Middle" alignment, the label is 'top-aligned' and overlaps the adjacent shapes. It appears the issue with the label itself is made worse the larger the font size is as well.

### Power BI

Power BI Desktop

### Power BI Version

September 2023

### Steps To Reproduce

![image](https://github.com/okviz/synoptic-panel-issues/assets/32279166/83233b20-1e18-4a3b-8868-417f513614fa)

### Sample report

[SynopticPanelLabelIssue.zip](https://github.com/okviz/synoptic-panel-issues/files/13464666/SynopticPanelLabelIssue.zip)

**Comment by danieleperilli** [comment] 2023-11-25 17:19
Duplicate of [#35](https://github.com/okviz/free-visuals/issues/35)

**Closed as completed by danieleperilli** 2023-11-25 17:19 UTC
Labels: bug, duplicate, v1 (legacy)

**Comment by icschiavi** [comment] 2024-07-08 20:38
@danieleperilli seems to be a bug reported 4 years ago and closed. Is there any fix expectation? Thanks!

**Comment by danieleperilli** [comment] 2024-07-09 16:46
@icschiavi Yes, you will release a new premium version of Synoptic Panel in September. It has been rewritten from scratch in the past year and will include several new features.
