### ISSUE TITLE
Failure to load the synoptic map in the Power BI Report Server version September 2023

### ISSUE THREAD

**Issue by ardeshirkalani** [okviz/synoptic-panel-issues#3] opened 2023-10-08 06:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello
I have upgraded the Power BI Report Server version to September 2023 and unfortunately the synoptic map does not load in this version.

### Power BI

Power BI Desktop

### Power BI Version

Power BI Report Server version September 2023

### Sample report

screenshot send to support@okviz.com

**Comment by danieleperilli** [comment] 2023-10-08 06:29
The issue is not related to our code, so we have asked Microsoft to investigate. It may be necessary to open a ticket with them. I will update this post when we receive a response.

**Comment by jcalmeida** [comment] 2023-10-19 22:10
Hello. I'm having the same issue. My okviz maps stopped working all at once. This issue is closed, but I don't see how it got fixed. What am I supposed to do to fix it? I'm using PowerBI Desktop for Report Server, on a local report file. I had an earlier version of power bi and just updated to september version. The issue was happening with the older version and still with the new version of powerbi.

**Comment by danieleperilli** [comment] 2023-10-25 17:53
@ardeshirkalani, @jcalmeida  Can you confirm that the issue is still there?

**Comment by edw246** [comment] 2023-10-26 05:32
The problem still exists, and Microsoft's response is that the issue is being worked on, and the fix will be available by the end of the month (October`23). We are waiting.

**Comment by bancobpi** [comment] 2023-10-26 08:18
@danieleperilli, yes it issue is still there.
@edw246, let's wait and see. Thanks.

**Comment by bancobpi** [comment] 2023-10-26 20:22
Yes, it still happens. Let's see if there is a fix soon.

**Comment by jcalmeida** [comment] 2023-10-26 20:24
@danieleperilli Yes, the issue is still here. @edw246 Where does microsoft say the problem is on their side and it will be fixed this month?

**Comment by edw246** [comment] 2023-10-27 04:50
@jcalmeida 
[here](https://community.fabric.microsoft.com/t5/Report-Server/PBI-Report-Server-September-2023-and-Synoptic-Panel/m-p/3459832) is the thread

**Comment by edw246** [comment] 2023-11-08 08:54
Hi all! Does anyone know when there will be an update that fixes the bug?
We didn’t roll back, hoping for a quick fix to the situation... we’re sitting without cards

**Comment by marcosqlbi** [comment] 2023-11-08 09:14
@edw246 you should open a support ticket with Microsoft - this way they should increase the prioritization of the fix and communicate directly when it is available. We did not receive updates from Microsoft yet.

**Comment by marcosqlbi** [comment] 2023-11-12 10:27
@edw246 @ardeshirkalani @jcalmeida Microsoft released a new version of Power BI Report Server on November 2, 2023, which fixed this issue:
[Power BI Report Server 15.0.1113.169](https://www.microsoft.com/en-us/download/details.aspx?id=57270)

**Closed as completed** 2024-01-08 19:31 UTC
Labels: platform bug
