### ISSUE TITLE
My visual is appearing blank when I publish to Power BI Cloud

### ISSUE THREAD

**Issue by AdriFon** [okviz/synoptic-panel-issues#7] opened 2024-01-15 15:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello everyone, I hope you're well
 
I'm working on a case where a system user can't see one of the visuals in a report in the Power BI Cloud environment. The visual in question is a map that was created using OKViz's Synoptic Panel. I've run some tests with the user who created the report and everything seems to be fine on his end. No error message is generated when accessing or publishing the report, the visual simply doesn't appear - it's blank - and only for the system user, for other users it works fine. Are there any limitations on user permissions? Is there any other test I can carry out with the administrator of this report to check what might be causing this problem?

### Power BI

Power BI Desktop, Power BI service

### Power BI Version

Power BI Cloud October 2023

### Sample report

The problem does not produce an error message. The only time it doesn't appear is when one of the users accesses the report; for the other users it works normally. What I find strange is that a similar report was created using Power BI On Premise September 2023 and the same user who is having the problem, can see the visual. Both visuals were created in the same way in both versions, but only in the Cloud version can the user not see it.

**Comment by danieleperilli** [comment] 2024-01-15 16:25
By Power BI Cloud October 2023 do you mean Power BI Server October 2023? If so, this is a duplicate of #3. Microsoft solved the problem on November 2023.

**Comment by AdriFon** [comment] 2024-01-15 17:44
No, the user can see the visual when published in our On Prem/Server environment (Power BI On-Premise September 2023), but not when published in our Cloud/Service environment (Power BI Cloud October 2023). And it's only the service user who can't see it in our cloud environment, because the map using the visual turns out to be blank. For the other users it seems to be normal.  This is why I would like to know if there is any limitation to using the visual, any other test that I should consider doing with the user to be able to identify the problem, since it doesn't show any error message.

**Comment by danieleperilli** [comment] 2024-01-15 19:03
Unfortunately, it seems that the problem is not code-related. There should not be a limitation. The best thing to do is probably to open a ticket with Microsoft.

**Comment by danieleperilli** [comment] 2024-02-01 07:01
Did you solve the issue with Microsoft?

**Closed as completed** 2024-02-13 18:04 UTC
Labels: bug, v1 (legacy)
